[package]
name = "fileopener"
version = "0.1.0"
authors = ["Toshihiro Kamiya <kamiya@mbj.nifty.com>"]
edition = "2018"

license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/tos-kamiya/fileopener"

[dependencies]
